version: "3.9"

services:
  db:
    image: "mysql:latest"
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=devdb
    ports:
      - "3306:3306"
    volumes:
      - bottle_mysql:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: bottle-mysql
    container_name: app
    restart: on-failure
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=devdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    volumes:
      - .:/src
    ports:
      - "8080:8080"
    command: "./compose/entrypoint.sh"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  bottle_mysql:
