version: "3.9"

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - django_pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
  
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django-celery
    container_name: worker
    restart: on-failure
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=
      - DJANGO_SECRET_KEY="django-insecure-k#s1dm=wuTrAprit&avu_tOhO!rubrldrapruqAkapedrln!2e"
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/web
    command: "./startworker.sh"
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django-celery
    container_name: flower
    restart: on-failure
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=
      - DJANGO_SECRET_KEY="django-insecure-k#s1dm=wuTrAprit&avu_tOhO!rubrldrapruqAkapedrln!2e"
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/web
    ports:
      - "5000:5000"
    command: "./startflower.sh"
    depends_on:
      - redis
      - worker

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django-celery
    container_name: app
    restart: on-failure
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=
      - DJANGO_SECRET_KEY="django-insecure-k#s1dm=wuTrAprit&avu_tOhO!rubrldrapruqAkapedrln!2e"
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    command: "./entrypoint.sh"
    depends_on:
      - postgres
      - redis
      - worker
      - flower


volumes:
  django_pgdata:
