version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5434:5432
    volumes:
      - flask_pgdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - backend

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/web
    ports:
    - 5000:5000
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://postgres:5432/flask_dev
      - SECRET_KEY=secret123
      - PGUSER=postgres
      - FLASK_APP=/web/run:app
    command: "./entrypoint.sh"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  flask_pgdata:
